### ISSUE TITLE
Web Console: add local reverse proxy for socket.io console instance

### ISSUE THREAD

**Issue by arawinters** [Senzing/entity-search-web-app#285]
Currently the way we tie the Web App’s embedded console to the instance of entity-search-web-app-console requires the user to know the public FQDN address of the console server. This introduces unnecessary complication to example formations since they have to be unique to the particular client’s set up.

I want to add a reverse proxy for that lives in the web server that forwards the socket to the instance of the console server. that way the user never has to configure anything, the interface will just try to open the socket up against the same address as the webserver, just on a different port.

**Comment by barrycaceres** [comment]
That sounds like a good solution.
------
Barry M. Caceres
Senzing, Chief of Application Services and Interfaces
***@***.******@***.***>



On May 11, 2022, at 7:22 PM, Ara Winters ***@***.******@***.***>> wrote:



Currently the way we tie the Web App’s embedded console to the instance of entity-search-web-app-console requires the user to know the public FQDN address of the console server. This introduces unnecessary complication to example formations since they have to be unique to the particular client’s set up.

I want to add a reverse proxy for that lives in the web server that forwards the socket to the instance of the console server. that way the user never has to configure anything, the interface will just try to open the socket up against the same address as the webserver, just on a different port.

**Comment by arawinters** [comment]
so, turns out it still required the docker configuration to specify the `SENZING_WEB_SERVER_URL` since it would pull from that as a fallback when not specifying the `SENZING_CONSOLE_SERVER_URL`.

I'm going to change it so that it will default to `localhost` when **_NEITHER_** variables are specified. that way if you're just doing a POC or dev work it will most likely work out of the box. You'll have to specify one(or both) for instances where it's running off it's own domain name(not on localhost).. which if you're doing that you should expect some configuration anyways.

reopening for new PR.
