### ISSUE TITLE
Improve behavior on web page refresh

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#385]
After bringing up a docker-compose stack, (e.g. https://github.com/Senzing/knowledge-base/tree/main/presentations/one-breath-minimal-stack) and searching for "Robert Smith", the URL in the address bar looks something like this:

> http://localhost:8251/search/results?refresh=1663618256817

A user then may hit the Web Browser's "Refresh" button. Instead of seeing the updated information for "Robert Smith", the user gets an error:

> http://localhost:8251/errors/unknown

A user's expectation would be that the contents of the web page would be refreshed,  not an error.

Can the this behavior be improved?

**Comment by arawinters** [comment]
so in order to do this we would have to either have the search parameters encoded in the URL or store them somewhere else(session or localstorage).. all of these options are kind of considered bad practice from an "exposes potential identifying information standpoint). . Once you click on an entity in the result the path does include the entity Id and the page can be refreshed, it's the interim step of _"I searched for last name and zip code"_ that gets washed away.

I'm not sure we should fix the issue, however _WE SHOULD_ redirect to the landing page so the user isn't presented with an error OR a route that shows a "Search Results Expired" message. 

*puts thinking cap on*  .. 
I suppose what we **_COULD_** do is store the search parameters in the browser session storage(so it's wiped away on tab/browser close) where the data store's key is a randomly generated number(like the "refresh" parameter in the uri) and pass that param in the uri.. so the uri would become 
`http://localhost:8251/search/1663618256817`
where the search params would be stored in session storage by the 1663618256817 key. On browser refresh for path `http://localhost:8251/search/${sessionStoreSearchKey}` would pull the `/${sessionStoreSearchKey}` out of the uri and see if there is a stored value and do the search again if so.. we could even salt the values and use the `${sessionStoreSearchKey}` as the decoding phrase if we wanted to get fancy. 

**yeah, that might work.**
